### ISSUE TITLE
add support for open-source ILP solver

### ISSUE THREAD

**Issue by martinlackner** [martinlackner/abcvoting#18]
Currently only Gurobi is supported. It would be nice to also support an open source ILP solver such as GLPK or LP_Solve, possibly via PuLP (https://pythonhosted.org/PuLP/index.html)

**Comment by martinlackner** [comment]
https://www.cvxpy.org/ might be a good alternative to PuLP

**Comment by DominikPeters** [comment]
There is also https://www.scipopt.org/

**Comment by lumbric** [comment]
Support for CVXPY (and therefore also for CBC, GLPK_MI and Scip) has been partially added in #27. I'll continue the next step in new PRs to support all optimization methods via CVXPY.

This should be a comfortable way to support three opensource solvers by using CVXPY as common API. PuLP and Pyomo are alternatives to CVXPY - tbh, I'm not sure if favorable or not, but atm we are heading for CVXPY as interface. Gurobi will be still usable using the `gurobipy` inteface, adding support for other interfaces than CVXPY and `gurobipy` is not planned at the moment.

**Comment by martinlackner** [comment]
I am closing this issue, as it is largely resolved. The CBC solver is directly available via mip (https://www.python-mip.com) and can be installed via pip. CVXPY is work-in-progress, but generally appears to be less reliable.
