### ISSUE TITLE
Proportional ranking

### ISSUE THREAD

**Issue by erelsgl** [martinlackner/abcvoting#54]
Is it possible to use the implemented rules to compute proportional rankings, such as in [this paper](https://arxiv.org/abs/1612.01434), or dynamic proportional rankings, such as in [this paper](https://arxiv.org/abs/2105.08043)? The methods are very similar - they are based on PAV or on Phragmen's rule; only the output format is different.

**Comment by martinlackner** [comment]
Yes, certainly. The easiest way would be adapt the corresponding functions to return a ranking. This should require very little effort. As far as I am aware the work on dynamic proportional rankings differs a bit more (and new voting rules are used), so there might be more to do. Note however that the source code of the dynamic proportional rankings paper is available: https://git.tu-berlin.de/jonas.israel/dpr

**Comment by erelsgl** [comment]
Getting back to this issue after almost 3  years... 
If I run a sequential algorithm such as seq-Phragmen, is the output list guaranteed to contain the candidates in the order they were selected by the rule?
My goal is to have a site similar to https://pref.tools/abcvoting/, but that shows a ranking rather than just a committee.
