### ISSUE TITLE
Comparison to other PAV implementations

### ISSUE THREAD

**Issue by nealmcb** [martinlackner/abcvoting#61]
I'm delighted to see this work - thank you!

I had previously Implemented Proportional Approval Voting in Python, at https://github.com/nealmcb/pr_voting_methods/

Warren D. Smith implemented it via a more general method in his CleanOptPRVote.c code, as referenced in my README.
His code is 100 times faster than mine, and uses a nice algorithm from Knuth to optimize the inner loop.

Yours of course is far more general and tests lots of voting method properties.

**Comment by martinlackner** [comment]
Interesting, thanks for the pointers! It's certainly helpful to have all kinds of implementations available for comparison.
