### ISSUE TITLE
Looking for ideas for undergraduate student project

### ISSUE THREAD

**Issue by erelsgl** [martinlackner/abcvoting#74]
I have a team of 3 students, who are in their final year of undergraduate studies in computer science. I am looking for a suitable project for them, that will also contribute to an open source project. The time-frame is an academic year - 9-10 months. So the project should have substantial content, but should not be an urgent fix. 

One option is to take a recent research paper with 3-4 algorithms, and implement the algorithms in the library. Another option is improving the efficiency and generality of existing algorithms. Other options are also possible, if they have enough content.

What are some ideas to projects that you will be happy to add into `abcvoting`?

**Comment by DominikPeters** [comment]
My impression is that the `[pabutools](https://github.com/pbvoting/pabutools/)` package is less mature than `abcvoting`, so there could be more opportunity there for improvements.

For `abcvoting`, one could add the Greedy Cohesive Rule (and perhaps variations of it), as well as the greedy justified candidate rule of [Markus Brill and Jannik Peters](https://arxiv.org/abs/2302.01989).
