### ISSUE TITLE
Updating the sampling module to use prefsampling instead of the current functions.

### ISSUE THREAD

**Issue by Simon-Rey** [martinlackner/abcvoting#75]
Hey!

With the development of prefsampling (https://github.com/COMSOC-Community/prefsampling) I am trying to update sampling procedures of other packages so that they use the samplers provided in prefsampling. This is done to avoid code repetition, mistakes etc...

I could start doing so for abcvoting, any objection before I start? Any requirements?

Simon.

**Comment by martinlackner** [comment]
Hi Simon!

Sounds like a great idea!
Here are a few nice-to-haves:
- the function signatures should remain the same (names, parameters)
- the unit tests still work ;)
- no additional requirements (except pref sampling)

Let me know if you have questions!

**Comment by Simon-Rey** [comment]
Yeah of course for all of that! Thanks :)
