### ISSUE TITLE
Can Seq-Phragmen be used to return a ranking?

### ISSUE THREAD

**Issue by erelsgl** [martinlackner/abcvoting#82]
If I run a sequential algorithm such as seq-Phragmen, is the output list guaranteed to contain the candidates in the order they were selected by the rule?
My goal is to have a site similar to https://pref.tools/abcvoting/, but that shows a ranking rather than just a committee.

**Comment by martinlackner** [comment]
Yes, absolutely. But it would make sense to adapt the code slightly if rankings are your main purpose
